# This file is part of visvalingamwyatt.
# https://github.com/fitnr/visvalingamwyatt
name: Publish to PyPi

on:
  release:
    types: [created, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: setup.cfg

      - name: Install build requirements
        run: |
          python -m pip install -U pip
          pip install build

      - run: make build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
